---
- name: Send notification to slack
  hosts: localhost


  vars:
    slack_token: ''
    slack_channel: "#devops"

  post_tasks:
    - name: send notification to slack
      slack:
        token: "{{slack_token}}"
        username: "ansible"
        channel: "{{slack_channel}}"
        color: "normal"
        msg: "testsend a notification with ansible !"
